version: "3.8"

services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Trantung09112005@
      MYSQL_DATABASE: techstore
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database